import { readable } from "svelte/store"

const fonts = readable({
  "Alegreya Sans": { name: "Alegreya+Sans", property: "'Alegreya Sans', sans-serif" },
  "Alegreya": { name: "Alegreya", property: "'Alegreya', serif" },
  "Anonymous Pro": { name: "Anonymous Pro", property: "'Anonymous Pro', serif" },
  "Archivo Narrow": { name: "Archivo Narrow", property: "'Archivo Narrow', sans-serif" },
  "BioRhyme": { name: "BioRhyme", property: "'BioRhyme', serif" },
  "Cardo": { name: "Cardo", property: "'Cardo', serif" },
  "Chivo": { name: "Chivo", property: "'Chivo', sans-serif" },
  "Cormorant": { name: "Cormorant", property: "'Cormorant', serif" },
  "Crimson Text": { name: "Crimson Text", property: "'Crimson Text', serif" },
  "Eczar": { name: "Eczar", property: "'Eczar', sans-serif" },
  "Fira Sans": { name: "Fira Sans", property: "'Fira Sans', sans-serif" },
  "IBM Plex Sans": { name: "IBM Plex Sans", property: "'IBM Plex Sans', sans-serif" },
  "Inconsolata": { name: "Inconsolata", property: "'Inconsolata', sans-serif" },
  "Inknut Antiqua": { name: "Inknut Antiqua", property: "'Inknut Antiqua', serif" },
  "Inter": { name: "Inter", property: "'Inter', sans-serif" },
  "Karla": { name: "Karla", property: "'Karla', sans-serif" },
  "Lato": { name: "Lato", property: "'Lato', sans-serif" },
  "Libre Baskerville": { name: "Libre Baskerville", property: "'Libre Baskerville', serif" },
  "Libre Franklin": { name: "Libre Franklin", property: "'Libre Franklin', sans-serif" },
  "Lora": { name: "Lora", property: "'Lora', serif" },
  "Merriweather": { name: "Merriweather", property: "'Merriweather', serif" },
  "Montserrat": { name: "Montserrat", property: "'Montserrat', sans-serif" },
  "Neuton": { name: "Neuton", property: "'Neuton', sans-serif" },
  "Noto Sans": { name: "Noto Sans", property: "'Noto Sans', sans-serif" },
  "Open Sans": { name: "Open Sans", property: "'Open Sans', sans-serif" },
  "Oswald": { name: "Oswald", property: "'Oswald', sans-serif" },
  "Playfair Display": { name: "Playfair Display", property: "'Playfair Display', serif" },
  "Poppins": { name: "Poppins", property: "'Poppins', sans-serif" },
  "Proza Libre": { name: "Proza Libre", property: "'Proza Libre', sans-serif" },
  "PT Sans": { name: "PT Sans", property: "'PT Sans', sans-serif" },
  "PT Serif": { name: "PT Serif", property: "'PT Serif', serif" },
  "Raleway": { name: "Raleway", property: "'Raleway', sans-serif" },
  "Roboto Slab": { name: "Roboto Slab", property: "'Roboto Slab', serif" },
  "Roboto": { name: "Roboto", property: "'Roboto', sans-serif" },
  "Rubik": { name: "Rubik", property: "'Rubik', sans-serif" },
  "Source Sans Pro": { name: "Source Sans Pro", property: "'Source Sans Pro', sans-serif" },
  "Source Serif Pro": { name: "Source Serif Pro", property: "'Source Serif Pro', serif" },
  "Space Grotesk": { name: "Space Grotesk", property: "'Space Grotesk', sans-serif" },
  "Space Mono": { name: "Space Mono", property: "'Space Mono', monospace" },
  "Spectral": { name: "Spectral", property: "'Spectral', sans-serif" },
  "Syne": { name: "Syne", property: "'Syne', sans-serif" },
  "Ubuntu": { name: "Ubuntu", property: "'Ubuntu', sans-serif" },
  "Work Sans": { name: "Work Sans", property: "'Work Sans', sans-serif" }
})

export { fonts }
